//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuideListFormatter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ClassOptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClassOptions defaultInstance = ((ClassOptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClassOptions())));
        
        public static ClassOptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hie")]
        public string HierophantName {
            get {
                return ((string)(this["HierophantName"]));
            }
            set {
                this["HierophantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inq")]
        public string InquisitorName {
            get {
                return ((string)(this["InquisitorName"]));
            }
            set {
                this["InquisitorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gua")]
        public string GuardianName {
            get {
                return ((string)(this["GuardianName"]));
            }
            set {
                this["GuardianName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SL")]
        public string SlayerName {
            get {
                return ((string)(this["SlayerName"]));
            }
            set {
                this["SlayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GL")]
        public string GladiatorName {
            get {
                return ((string)(this["GladiatorName"]));
            }
            set {
                this["GladiatorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CH")]
        public string ChampionName {
            get {
                return ((string)(this["ChampionName"]));
            }
            set {
                this["ChampionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public string JuggernautName {
            get {
                return ((string)(this["JuggernautName"]));
            }
            set {
                this["JuggernautName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string ChieftainName {
            get {
                return ((string)(this["ChieftainName"]));
            }
            set {
                this["ChieftainName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string BerserkerName {
            get {
                return ((string)(this["BerserkerName"]));
            }
            set {
                this["BerserkerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raid")]
        public string RaiderName {
            get {
                return ((string)(this["RaiderName"]));
            }
            set {
                this["RaiderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PF")]
        public string PathfinderName {
            get {
                return ((string)(this["PathfinderName"]));
            }
            set {
                this["PathfinderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dead")]
        public string DeadeyeName {
            get {
                return ((string)(this["DeadeyeName"]));
            }
            set {
                this["DeadeyeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trickster")]
        public string TricksterName {
            get {
                return ((string)(this["TricksterName"]));
            }
            set {
                this["TricksterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assassin")]
        public string AssassinName {
            get {
                return ((string)(this["AssassinName"]));
            }
            set {
                this["AssassinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saboteur")]
        public string SaboteurName {
            get {
                return ((string)(this["SaboteurName"]));
            }
            set {
                this["SaboteurName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OCC")]
        public string OccultistName {
            get {
                return ((string)(this["OccultistName"]));
            }
            set {
                this["OccultistName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ELE")]
        public string ElementalistName {
            get {
                return ((string)(this["ElementalistName"]));
            }
            set {
                this["ElementalistName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NEC")]
        public string NecromancerName {
            get {
                return ((string)(this["NecromancerName"]));
            }
            set {
                this["NecromancerName"] = value;
            }
        }
    }
}
